### Extract data from Reliefweb API

#### Load jsonlite package
library(jsonlite) 

#### Assign extracted API data to "rwjobs"
rwjobsraw1 <- fromJSON("http://api.reliefweb.int/v1/jobs?limit=2&filter[field]=date.created&filter[value][from]=2016-05-24T00:00:00%2B00:00&filter[value][to]=2016-05-30T00:00:00%2B00:00&&fields[include][]title&fields[include][]=body&fields[include][]=theme&fields[include][]=country&fields[include][]=type&fields[include][]=experience&fields[include][]=career_categories")

#### Assign data set to "rwjobs1" and review column names
rwjobs1 <- rwjobsraw1$data$fields
colnames(rwjobs1)

#### View data set
View(rwjobs1)

### Unlist nested lists

#### Load plyr package
library(plyr)

#### Unlist column entries
rwjobs1$theme <- llply(rwjobs1$theme, unlist)
rwjobs1$type <- llply(rwjobs1$type, unlist)
rwjobs1$experience <- llply(rwjobs1$experience, unlist)
rwjobs1$career_categories <- llply(rwjobs1$career_categories, unlist)
rwjobs1$country <- llply(rwjobs1$country, unlist)

### Clean dataset 

#### Remove unneccesary characters and split strings 
rwjobs1$type <- gsub("\\c\\(", "", rwjobs1$type)
rwjobs1$type <- gsub("\"", "", rwjobs1$type)
rwjobs1$type <- gsub("\\)", "", rwjobs1$type)
rwjobs1$type <- as.character(rwjobs1$type)
type_split <- strsplit(rwjobs1$type, split = ",")
select_el <- function(x, index) {x[index]}
type_id <- lapply(type_split, select_el, index = 1) 
type_name <- lapply(type_split, select_el, index = 2) 
rwjobs1$type_id <- as.character(type_id)
rwjobs1$type_name <- as.character(type_name)
rwjobs1$type <- NULL

rwjobs1$career_categories <- gsub("\\c\\(", "", rwjobs1$career_categories)
rwjobs1$career_categories <- gsub("\"", "", rwjobs1$career_categories)
rwjobs1$career_categories <- gsub("\\)", "", rwjobs1$career_categories)
rwjobs1$career_categories <- as.character(rwjobs1$career_categories)
select_el <- function(x, index) {x[index]}
career_categories_id <- lapply(career_categories_split, select_el, index = 1) 
career_categories_name <- lapply(career_categories_split, select_el, index = 2) 
rwjobs1$career_categories_id <- as.character(career_categories_id)
rwjobs1$career_categories_name <- as.character(career_categories_name)
rwjobs1$career_categories <- NULL

rwjobs1$theme <- gsub("\\c\\(", "", rwjobs1$theme)
rwjobs1$theme <- gsub("\"", "", rwjobs1$theme)
rwjobs1$theme <- gsub("\\)", "", rwjobs1$theme)
rwjobs1$theme <- as.character(rwjobs1$theme)
theme_split <- strsplit(rwjobs1$theme, split = ",")
select_el <- function(x, index) {x[index]}
theme_id <- lapply(theme_split, select_el, index = 1) 
theme_name <- lapply(theme_split, select_el, index = 2) 
rwjobs1$theme_id <- as.character(theme_id)
rwjobs1$theme_name <- as.character(theme_name)
rwjobs1$theme <- NULL

rwjobs1$experience <- gsub("\\c\\(", "", rwjobs1$experience)
rwjobs1$experience <- gsub("\"", "", rwjobs1$experience)
rwjobs1$experience <- gsub("\\years\\)", "", rwjobs1$experience)
rwjobs1$experience <- as.character(rwjobs1$experience)
experience_split <- strsplit(rwjobs1$experience, split = ",")
select_el <- function(x, index) {x[index]}
experience_id <- lapply(experience_split, select_el, index = 1) 
experience_years <- lapply(experience_split, select_el, index = 2) 
rwjobs1$experience_id <- as.character(experience_id)
rwjobs1$experience_years <- as.character(experience_years)
rwjobs1$experience_id <- NULL
rwjobs1$experience <- NULL

rwjobs1$country <- gsub("\\c\\(", "", rwjobs1$country)
rwjobs1$country <- gsub("\"", "", rwjobs1$country)
rwjobs1$country <- gsub("\\)", "", rwjobs1$country)
rwjobs1$country <- as.character(rwjobs1$country)
country_split <- strsplit(rwjobs1$country, split = ",")
select_el <- function(x, index) {x[index]}
country_href <- lapply(country_split, select_el, index = 1) 
country_id <- lapply(country_split, select_el, index = 2) 
country_location1 <- lapply(country_split, select_el, index = 3) 
country_location2 <- lapply(country_split, select_el, index = 4) 
country_name <- lapply(country_split, select_el, index = 5) 
country_iso <- lapply(country_split, select_el, index = 6)
country_sn <- lapply(country_split, select_el, index = 7)
rwjobs1$country_id <- as.character(country_id)
rwjobs1$country_name <- as.character(country_name)
rwjobs1$country <- NULL 

### Create columns for languages

#### Load stringr package
library(stringr)

#### Create columns based on language keywords in the "body" and "country_name" columns
rwjobs1$French <- str_match(rwjobs1$body, "French")
rwjobs1$French <- ifelse(rwjobs1$French=="French", 1, 0)
rwjobs1$French2 <- str_match(rwjobs1$body, "pour")
rwjobs1$French2 <- ifelse(rwjobs1$French2=="pour", 1, 0)
rwjobs1$French3 <- str_match(rwjobs1$country_name, "France")
rwjobs1$French3 <- ifelse(rwjobs1$French3=="France", 1, 0)
rwjobs1$English <- str_match(rwjobs1$body, "English")
rwjobs1$English <- ifelse(rwjobs1$English=="English", 1, 0)
rwjobs1$English2 <- str_match(rwjobs1$country_name, "United States of America")
rwjobs1$English2 <- ifelse(rwjobs1$English2=="United States of America", 1, 0)
rwjobs1$Arabic <- str_match(rwjobs1$body, "Arabic")
rwjobs1$Arabic <- ifelse(rwjobs1$Arabic=="Arabic", 1, 0)
rwjobs1$Spanish <- str_match(rwjobs1$body, "Spanish")
rwjobs1$Spanish <- ifelse(rwjobs1$Spanish=="Spanish", 1, 0)
rwjobs1$Spanish2 <- str_match(rwjobs1$country_name, "Spain")
rwjobs1$Spanish2 <- ifelse(rwjobs1$Spanish2=="Spain", 1, 0)
rwjobs1$Italian <- str_match(rwjobs1$body, "Italian")
rwjobs1$Italian <- ifelse(rwjobs1$Italian=="Italian", 1, 0)
rwjobs1$Italian2 <- str_match(rwjobs1$country_name, "Italy")
rwjobs1$Italian2 <- ifelse(rwjobs1$Italian2=="Italy", 1, 0)
rwjobs1$local <- str_match(rwjobs1$body, "local language")
rwjobs1$local <- ifelse(rwjobs1$local=="local language", 1, 0)

### Save dataset into a csv file, amending the csv file name depending on the batch of data extracted
write.csv(rwjobs1, "rwjobs1.csv")

### Combine cleaned dataset
rwjobs1 <- read.csv("C:/Users/elizajv/Documents/rwjobs1.csv", 1)
rwjobs2 <- read.csv("C:/Users/elizajv/Documents/rwjobs2.csv", 1)
rwjobs3 <- read.csv("C:/Users/elizajv/Documents/rwjobs3.csv", 1)
rwjobs4 <- read.csv("C:/Users/elizajv/Documents/rwjobs4.csv", 1)
rwjobs5 <- read.csv("C:/Users/elizajv/Documents/rwjobs5.csv", 1)
rwjobsall <- rbind(rwjobs1, rwjobs2, rwjobs3, rwjobs4, rwjobs5)

### View combined dataset
View(rwjobsall)
